from telebot import types

reg = types.InlineKeyboardMarkup()
reg.row(types.InlineKeyboardButton("Зарегистрироваться✅", callback_data="reg"))

choice_brand = types.InlineKeyboardMarkup(row_width=1)
apple = types.InlineKeyboardButton("Apple", callback_data="apple")
huawei = types.InlineKeyboardButton("Huawei, Honor", callback_data="huawei")
samsung = types.InlineKeyboardButton("Samsung", callback_data="samsung")
xiaomi = types.InlineKeyboardButton("Xiaomi", callback_data="xiaomi")
choice_brand.row(apple, huawei, samsung, xiaomi)

admin = types.ReplyKeyboardMarkup(True)
admin.add("Пользователи👤", "Начислить cashback💰")
admin.add("Установить номер📞", "Назначить админа🦸")
admin.add("Списать балы🙍", "Вернуться в меню👨‍💻")

a = '🙊'
profile = types.ReplyKeyboardMarkup(True)
profile.add("Сделать заказ⚙️", "Мой профиль👤")
profile.add("Связаться с мастером🧑‍🔧", "Узнать цену💵")

dostavka = types.ReplyKeyboardMarkup(True)
dostavka.add("Вызвать курьера🏎", "Приеду в мастерскую🔧")
dostavka.add("Вернуться в меню👨‍💻")

delete = types.InlineKeyboardMarkup()
del1 = types.InlineKeyboardButton("❌Закрыть", callback_data="delete")
delete.row(del1)

devices = types.InlineKeyboardMarkup()
phone = types.InlineKeyboardButton("📱Телефон", callback_data="phone")
tablet = types.InlineKeyboardButton("📲Планшет", callback_data="tablet")
laptop = types.InlineKeyboardButton("💻Ноутбук", callback_data="laptop")
tv = types.InlineKeyboardButton("🖥Телевизор", callback_data="tv")
devices.row(phone, tablet)
devices.row(laptop, tv)
devices.row(del1)

choice_brand = types.InlineKeyboardMarkup(row_width=1)
apple = types.InlineKeyboardButton("Apple", callback_data="apple")
huawei = types.InlineKeyboardButton("Huawei", callback_data="huawei")
honor = types.InlineKeyboardButton("Honor", callback_data="honor")
samsung = types.InlineKeyboardButton("Samsung", callback_data="samsung")
xiaomi = types.InlineKeyboardButton("Xiaomi", callback_data="xiaomi")
choice_brand.add(apple, huawei, honor, samsung, xiaomi, del1)

apple_buttons = types.InlineKeyboardMarkup(row_width=3)
apple_b1 = types.InlineKeyboardButton("5/5с/5S/SE", callback_data="iPhone 5/5с/5S/SE")
apple_b2 = types.InlineKeyboardButton(" 6 ", callback_data="iPhone 6")
apple_b3 = types.InlineKeyboardButton(" 6+ ", callback_data="iPhone 6 plus")
apple_b4 = types.InlineKeyboardButton(" 6s ", callback_data="iPhone 6s")
apple_b5 = types.InlineKeyboardButton(" 6s+ ", callback_data="iPhone 6s plus")
apple_b6 = types.InlineKeyboardButton(" 7 ", callback_data="iPhone 7")
apple_b7 = types.InlineKeyboardButton(" 7+ ", callback_data="iPhone 7 plus")
apple_b8 = types.InlineKeyboardButton(" 8 ", callback_data="iPhone 8")
apple_b9 = types.InlineKeyboardButton(" 8+ ", callback_data="iPhone 8 plus")
apple_b10= types.InlineKeyboardButton(" X ", callback_data="iPhone X")
apple_b11 = types.InlineKeyboardButton(" XS ", callback_data="iPhone XS")
apple_b12 = types.InlineKeyboardButton("XS MAX", callback_data="iPhone XS MAX")
apple_b13 = types.InlineKeyboardButton(" 11 ", callback_data="iPhone 11")
apple_b14 = types.InlineKeyboardButton("11 Pro", callback_data="iPhone 11 Pro")
apple_b15 = types.InlineKeyboardButton("11 Pro Max", callback_data="iPhone 11 Pro Max")
apple_b16 = types.InlineKeyboardButton(" XR ", callback_data="iPhone XR")
apple_b17 = types.InlineKeyboardButton("watch", callback_data="watch")
apple_b18 = types.InlineKeyboardButton("ipad", callback_data="ipad")
apple_buttons.add(apple_b1, apple_b2, apple_b3, apple_b4, apple_b5, apple_b6, apple_b7, apple_b8, apple_b9, apple_b10,
                  apple_b11, apple_b12, apple_b13, apple_b14, apple_b15, apple_b16, apple_b17, apple_b18)
apple_buttons.row(del1)

huawei_buttons = types.InlineKeyboardMarkup()
hu_b1 = types.InlineKeyboardButton("7A/Y5 Prime 2018/9s/Y5p/7A/7C/Y6 Prime 2018", callback_data="Honor 7A")
hu_b2 = types.InlineKeyboardButton("8/8 Lite/P8 Lite 2017/8 Pro/8c/8x", callback_data="Honor 8X")
hu_b3 = types.InlineKeyboardButton("8A/8A Pro/8A Prime", callback_data="Honor 8A")
hu_b4 = types.InlineKeyboardButton("9/9A/Y6p/9 Lite", callback_data="Honor 9A")
hu_b5 = types.InlineKeyboardButton("10 Lite/10i/20i/10X Lite/P Smart 2021", callback_data="Honor 10")
hu_b6 = types.InlineKeyboardButton("20 lite/20/20 Pro/Nova 5T", callback_data="Honor 20")
hu_b7 = types.InlineKeyboardButton("Mate 10/Mate 10 Pro/Mate 10 Lite", callback_data="Huawei Mate 10")
hu_b8 = types.InlineKeyboardButton("Nova 2i/Mate 20/Mate 20 Lite", callback_data="Huawei Mate 20")
hu_b8_2 = types.InlineKeyboardButton("Nova", callback_data="Huawei Nova")
hu_b9 = types.InlineKeyboardButton("Nova 2/Nova 2 Plus", callback_data="Huawei Nova 2")
hu_b10 = types.InlineKeyboardButton("Nova 3", callback_data="Huawei Nova 3")
hu_b11 = types.InlineKeyboardButton("P9 Lite", callback_data="Huawei P9")
hu_b12 = types.InlineKeyboardButton("P10 Lite", callback_data="Huawei P10")
hu_b13 = types.InlineKeyboardButton("P30/P30 lite/20s", callback_data="Huawei P30")
hu_b14 = types.InlineKeyboardButton("P40 Lite E/9C/Y7p/P40 Lite/Nova 6 SE", callback_data="Huawei P40")
hu_b15 = types.InlineKeyboardButton("P Smart Z/9X/P Smart 2019/P Smart", callback_data="Huawei P Smart")
hu_b16 = types.InlineKeyboardButton("Y6 2019/Y6 Prime 2019/Y6 Pro 2019/Y6s", callback_data="Huawei Y6")
huawei_buttons.row(hu_b1)
huawei_buttons.row(hu_b2)
huawei_buttons.add(hu_b3,hu_b4)
huawei_buttons.row(hu_b5)
huawei_buttons.row(hu_b6)
huawei_buttons.row(hu_b7)
huawei_buttons.row(hu_b8)
huawei_buttons.row(hu_b8_2)
huawei_buttons.add(hu_b8,hu_b9,hu_b10,hu_b11,hu_b12,hu_b13)
huawei_buttons.row(hu_b14)
huawei_buttons.row(hu_b15)
huawei_buttons.row(hu_b16)

huawei_buttons.row(del1)