name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
#  build_and_pub:
#    runs-on: ubuntu-latest
#    env:
#      LOGIN: ${{ secrets.DOCKER_LOGIN }}
#      NAME: ${{ secrets.DOCKER_NAME }}
#    steps:
#      - name: Login to docker.io
#        run: echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
#      - uses: actions/checkout@v1
#      - name: Build image
#        run: docker build -t $LOGIN/$NAME:${GITHUB_SHA} -f Dockerfile .
#      - name: Push image to docker.io
#        run: docker push $LOGIN/$NAME:${GITHUB_SHA}

  deploy:
    runs-on: ubuntu-latest
#    needs: [ build_and_pub ]
    steps:
      - name: Set tag to env
        run: env
      - name: Send webhook for deploy
        run: |
          curl --silent --show-error --fail --location --request POST '185.174.136.216:5000' \
            --header 'content-type: application/json' \
            --header 'Authorization: 12345' \
            --data-raw '{"owner": "sav116",
            "repository": "master_bot",
            "tag": "$GITHUB_SHA"}'
